// src/components/BottomPanel.tsx
import { useEffect, useRef, useState } from 'react';
import { Terminal } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';
import '@xterm/xterm/css/xterm.css';
import { startTerminal, runTask } from '../terminal/bridge';
import type { TermHandle } from '../terminal/bridge';
import { SHELLS } from '../types';
import type { IdeApi } from '../types';
import { CloseIcon, PlayIcon, RefreshIcon, TrashIcon } from './icons';

const TERM_THEME = {
  background: '#0b0e17',
  foreground: '#d5e0f7',
  cursor: '#67e8f9',
  cursorAccent: '#0b0e17',
  selectionBackground: '#2a4d7a66',
  black: '#0b0e17',
  brightBlack: '#5b6a8c',
  red: '#f87171',
  brightRed: '#f87171',
  green: '#34d399',
  brightGreen: '#34d399',
  yellow: '#fbbf24',
  brightYellow: '#fbbf24',
  blue: '#7aa2ff',
  brightBlue: '#7aa2ff',
  magenta: '#f472b6',
  brightMagenta: '#f472b6',
  cyan: '#22d3ee',
  brightCyan: '#22d3ee',
  white: '#d5e0f7',
  brightWhite: '#ffffff',
};

// ─── Нижняя панель: Терминал | Задачи ─────────────────────────────────────

export default function BottomPanel({ ide }: { ide: IdeApi }) {
  return (
    <div className="bottom-panel">
      <div className="bottom-tabs">
        <button
          className={`bottom-tab ${ide.panelTab === 'terminal' ? 'active' : ''}`}
          onClick={() => ide.setPanelTab('terminal')}
        >
          Терминал
        </button>
        <button
          className={`bottom-tab ${ide.panelTab === 'tasks' ? 'active' : ''}`}
          onClick={() => ide.setPanelTab('tasks')}
        >
          Задачи
        </button>
        <div className="bottom-tabs-spacer" />
        <button
          className="bottom-close"
          title="Закрыть панель (Ctrl+`)"
          onClick={() => ide.setPanelOpen(false)}
        >
          <CloseIcon size={13} />
        </button>
      </div>
      {ide.panelTab === 'terminal' ? <TerminalTab ide={ide} /> : <TasksTab ide={ide} />}
    </div>
  );
}

// ─── Терминал ─────────────────────────────────────────────────────────────

function TerminalTab({ ide }: { ide: IdeApi }) {
  const hostRef = useRef<HTMLDivElement | null>(null);
  const termRef = useRef<Terminal | null>(null);
  const handleRef = useRef<TermHandle | null>(null);
  const [running, setRunning] = useState(false);
  const [restartKey, setRestartKey] = useState(0);
  const shell = ide.settings.shell;

  // создаём терминал заново при смене оболочки или перезапуске
  useEffect(() => {
    const host = hostRef.current;
    if (!host) return;
    let disposed = false;
    handleRef.current?.kill();
    handleRef.current = null;

    const term = new Terminal({
      cursorBlink: true,
      fontSize: ide.settings.terminalFontSize,
      fontFamily: ide.settings.fontFamily,
      scrollback: 5000,
      theme: TERM_THEME,
    });
    const fit = new FitAddon();
    term.loadAddon(fit);
    term.open(host);
    term.onData((d) => handleRef.current?.write(d));
    termRef.current = term;
    setRunning(true);

    const cwd = ide.workspace?.rootPath ?? '/';
    startTerminal(shell, cwd, 80, 24)
      .then((h) => {
        if (disposed) {
          h.kill();
          return;
        }
        h.onData((d) => {
          if (disposed) return;
          try {
            term.write(d);
          } catch {
            /* ignore */
          }
        });
        h.onExit(() => {
          if (disposed) return;
          try {
            term.write('\r\n\x1b[90m[процесс завершён]\x1b[0m\r\n');
          } catch {
            /* ignore */
          }
          setRunning(false);
        });
        handleRef.current = h;
        requestAnimationFrame(() => {
          try {
            if (host.offsetWidth > 0 && host.offsetHeight > 0) {
              fit.fit();
              h.resize(term.cols, term.rows);
            }
          } catch {
            /* ignore */
          }
        });
      })
      .catch((e) => {
        if (disposed) return;
        try {
          term.write(`\r\n\x1b[31mОшибка: ${String(e)}\x1b[0m\r\n`);
        } catch {
          /* ignore */
        }
        setRunning(false);
      });

    const ro = new ResizeObserver(() => {
      try {
        if (host.offsetWidth > 0 && host.offsetHeight > 0) {
          fit.fit();
          handleRef.current?.resize(term.cols, term.rows);
        }
      } catch {
        /* ignore */
      }
    });
    ro.observe(host);

    return () => {
      disposed = true;
      ro.disconnect();
      handleRef.current?.kill();
      handleRef.current = null;
      term.dispose();
      termRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [shell, restartKey]);

  // подстройка размера шрифта без пересоздания
  useEffect(() => {
    if (termRef.current) {
      termRef.current.options.fontSize = ide.settings.terminalFontSize;
      termRef.current.options.fontFamily = ide.settings.fontFamily;
    }
  }, [ide.settings.terminalFontSize, ide.settings.fontFamily]);

  return (
    <>
      <div className="bottom-toolbar">
        <select
          className="select shell-select"
          value={shell}
          title="Выбрать оболочку (перезапустит терминал)"
          onChange={(e) => ide.updateSettings({ shell: e.target.value as never })}
        >
          {SHELLS.map((s) => (
            <option key={s.id} value={s.id}>
              {s.label}
            </option>
          ))}
        </select>
        <button className="btn-icon" title="Перезапустить терминал" onClick={() => setRestartKey((k) => k + 1)}>
          <RefreshIcon />
        </button>
        <span className="term-status">{running ? '● подключено' : '○ остановлено'}</span>
        <div className="bottom-tabs-spacer" />
      </div>
      <div className="term-host" ref={hostRef} />
    </>
  );
}

// ─── Задачи (команды из tinyide.toml) ─────────────────────────────────────

function TasksTab({ ide }: { ide: IdeApi }) {
  const [name, setName] = useState('build');
  const [output, setOutput] = useState('');
  const [running, setRunning] = useState(false);
  const outRef = useRef<HTMLDivElement | null>(null);
  const names = Object.keys(ide.taskCommands);

  useEffect(() => {
    if (!names.includes(name) && names.length) setName(names[0]);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [names.join(',')]);

  useEffect(() => {
    if (ide.taskRequest) {
      setName(ide.taskRequest.name);
      run(ide.taskRequest.command);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ide.taskRequest?.nonce]);

  const run = async (command?: string) => {
    const cmd = command ?? ide.taskCommands[name];
    if (!cmd || running) return;
    setRunning(true);
    setOutput('');
    const cwd = ide.workspace?.rootPath ?? '/';
    const h = await runTask(cmd, cwd);
    h.onOutput((t) => setOutput((o) => o + t));
    h.onExit((code) => {
      setOutput((o) => o + `\n\x1b[90m[задача завершена · код ${code}]\x1b[0m\n`);
      setRunning(false);
    });
  };

  useEffect(() => {
    outRef.current?.scrollTo({ top: outRef.current.scrollHeight });
  }, [output]);

  return (
    <div className="tasks-wrap">
      <div className="bottom-toolbar">
        <button
          className="btn-icon primary"
          title="Запустить"
          onClick={() => run()}
          disabled={running}
        >
          <PlayIcon />
        </button>
        <select
          className="select shell-select"
          value={name}
          onChange={(e) => setName(e.target.value)}
          title="Команда из секции [commands] в tinyide.toml"
        >
          {names.map((n) => (
            <option key={n} value={n}>
              {n}: {ide.taskCommands[n]}
            </option>
          ))}
        </select>
        <button className="btn-icon" title="Очистить вывод" onClick={() => setOutput('')}>
          <TrashIcon />
        </button>
        <div className="bottom-tabs-spacer" />
      </div>
      <div className="task-output" ref={outRef}>
        {output === '' && !running && (
          <span className="task-hint">
            Выбери команду (build / run / test — из секции [commands] файла tinyide.toml) и нажми ▶
          </span>
        )}
        {output.split('\n').map((line, i) => {
          const styled = line
            .replace(/\x1b\[90m/g, '<span class="tc-dim">')
            .replace(/\x1b\[31m/g, '<span class="tc-red">')
            .replace(/\x1b\[32m/g, '<span class="tc-green">')
            .replace(/\x1b\[36m/g, '<span class="tc-cyan">')
            .replace(/\x1b\[0m/g, '</span>');
          return <div key={i} dangerouslySetInnerHTML={{ __html: styled || '&nbsp;' }} />;
        })}
      </div>
    </div>
  );
}

// src/components/BottomPanel.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from 'vue';
import { Terminal } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';
import '@xterm/xterm/css/xterm.css';
import { startTerminal, runTask } from '../terminal/bridge';
import type { TermHandle } from '../terminal/bridge';
import { SHELLS } from '../types';
import { store } from '../store';
import AppIcon from './AppIcon.vue';

const TERM_THEME = {
  background: '#0b0e17',
  foreground: '#d5e0f7',
  cursor: '#67e8f9',
  cursorAccent: '#0b0e17',
  selectionBackground: '#2a4d7a66',
  black: '#0b0e17',
  brightBlack: '#5b6a8c',
  red: '#f87171',
  brightRed: '#f87171',
  green: '#34d399',
  brightGreen: '#34d399',
  yellow: '#fbbf24',
  brightYellow: '#fbbf24',
  blue: '#7aa2ff',
  brightBlue: '#7aa2ff',
  magenta: '#f472b6',
  brightMagenta: '#f472b6',
  cyan: '#22d3ee',
  brightCyan: '#22d3ee',
  white: '#d5e0f7',
  brightWhite: '#ffffff',
};

// ─── Терминал ──────────────────────────────────────────────────────────────
const hostRef = ref<HTMLDivElement | null>(null);
const running = ref(false);
const restartKey = ref(0);
let term: Terminal | null = null;
let fit: FitAddon | null = null;
let handle: TermHandle | null = null;
let ro: ResizeObserver | null = null;
let disposed = false;

async function bootTerminal() {
  const host = hostRef.value;
  if (!host) return;
  handle?.kill();
  handle = null;
  term?.dispose();
  term = null;

  term = new Terminal({
    cursorBlink: true,
    fontSize: store.settings.terminalFontSize,
    fontFamily: store.settings.fontFamily,
    scrollback: 5000,
    theme: TERM_THEME,
  });
  fit = new FitAddon();
  term.loadAddon(fit);
  term.open(host);
  term.onData((d) => handle?.write(d));
  running.value = true;

  const cwd = store.workspace?.rootPath ?? '/';
  try {
    const h = await startTerminal(store.settings.shell, cwd, 80, 24);
    if (disposed) {
      h.kill();
      return;
    }
    h.onData((d) => {
      if (disposed || !term) return;
      try {
        term.write(d);
      } catch {
        /* ignore */
      }
    });
    h.onExit(() => {
      if (disposed || !term) return;
      try {
        term.write('\r\n\x1b[90m[процесс завершён]\x1b[0m\r\n');
      } catch {
        /* ignore */
      }
      running.value = false;
    });
    handle = h;
    requestAnimationFrame(() => {
      try {
        if (host.offsetWidth > 0 && host.offsetHeight > 0) {
          fit?.fit();
          h.resize(term!.cols, term!.rows);
        }
      } catch {
        /* ignore */
      }
    });
  } catch (e) {
    if (!disposed && term) {
      try {
        term.write(`\r\n\x1b[31mОшибка: ${String(e)}\x1b[0m\r\n`);
      } catch {
        /* ignore */
      }
    }
    running.value = false;
  }
}

onMounted(() => {
  disposed = false;
  bootTerminal();
  ro = new ResizeObserver(() => {
    try {
      if (hostRef.value && hostRef.value.offsetWidth > 0 && hostRef.value.offsetHeight > 0) {
        fit?.fit();
        handle?.resize(term!.cols, term!.rows);
      }
    } catch {
      /* ignore */
    }
  });
  if (hostRef.value) ro.observe(hostRef.value);
});

onUnmounted(() => {
  disposed = true;
  ro?.disconnect();
  handle?.kill();
  handle = null;
  term?.dispose();
  term = null;
});

watch(
  () => store.settings.shell,
  () => bootTerminal()
);
watch(restartKey, () => bootTerminal());
watch(
  () => [store.settings.terminalFontSize, store.settings.fontFamily],
  () => {
    if (term) {
      term.options.fontSize = store.settings.terminalFontSize;
      term.options.fontFamily = store.settings.fontFamily;
    }
  }
);

// ─── Задачи ────────────────────────────────────────────────────────────────
const taskName = ref('build');
const output = ref('');
const taskRunning = ref(false);
const outEl = ref<HTMLDivElement | null>(null);

watch(
  () => Object.keys(store.taskCommands).join(','),
  () => {
    if (!Object.keys(store.taskCommands).includes(taskName.value) && Object.keys(store.taskCommands).length) {
      taskName.value = Object.keys(store.taskCommands)[0];
    }
  }
);

watch(
  () => store.taskRequest?.nonce,
  (n) => {
    if (n && store.taskRequest) {
      taskName.value = store.taskRequest.name;
      run(store.taskRequest.command);
    }
  }
);

watch(output, () => {
  outEl.value?.scrollTo({ top: outEl.value.scrollHeight });
});

async function run(command?: string) {
  const cmd = command ?? store.taskCommands[taskName.value];
  if (!cmd || taskRunning.value) return;
  taskRunning.value = true;
  output.value = '';
  const cwd = store.workspace?.rootPath ?? '/';
  const h = await runTask(cmd, cwd);
  h.onOutput((t) => (output.value += t));
  h.onExit((code) => {
    output.value += `\n\x1b[90m[задача завершена · код ${code}]\x1b[0m\n`;
    taskRunning.value = false;
  });
}

const styledLines = (line: string) =>
  line
    .replace(/\x1b\[90m/g, '<span class="tc-dim">')
    .replace(/\x1b\[31m/g, '<span class="tc-red">')
    .replace(/\x1b\[32m/g, '<span class="tc-green">')
    .replace(/\x1b\[36m/g, '<span class="tc-cyan">')
    .replace(/\x1b\[0m/g, '</span>');
</script>

<template>
  <div class="bottom-panel">
    <div class="bottom-tabs">
      <button class="bottom-tab" :class="{ active: store.panelTab === 'terminal' }" @click="store.setPanelTab('terminal')">Терминал</button>
      <button class="bottom-tab" :class="{ active: store.panelTab === 'tasks' }" @click="store.setPanelTab('tasks')">Задачи</button>
      <div class="bottom-tabs-spacer" />
      <button class="bottom-close" title="Закрыть панель (Ctrl+`)" @click="store.setPanelOpen(false)">
        <AppIcon name="close" :size="13" />
      </button>
    </div>

    <template v-if="store.panelTab === 'terminal'">
      <div class="bottom-toolbar">
        <select class="select shell-select" :value="store.settings.shell" title="Выбрать оболочку (перезапустит терминал)" @change="(e) => store.updateSettings({ shell: (e.target as HTMLSelectElement).value as never })">
          <option v-for="s in SHELLS" :key="s.id" :value="s.id">{{ s.label }}</option>
        </select>
        <button class="btn-icon" title="Перезапустить терминал" @click="restartKey++">
          <AppIcon name="refresh" />
        </button>
        <span class="term-status">{{ running ? '● подключено' : '○ остановлено' }}</span>
        <div class="bottom-tabs-spacer" />
      </div>
      <div ref="hostRef" class="term-host" />
    </template>

    <template v-else>
      <div class="tasks-wrap">
        <div class="bottom-toolbar">
          <button class="btn-icon primary" title="Запустить" :disabled="taskRunning" @click="run()">
            <AppIcon name="play" />
          </button>
          <select class="select shell-select" :value="taskName" title="Команда из секции [commands] в tinyide.toml" @change="(e) => (taskName = (e.target as HTMLSelectElement).value)">
            <option v-for="(cmd, n) in store.taskCommands" :key="n" :value="n">{{ n }}: {{ cmd }}</option>
          </select>
          <button class="btn-icon" title="Очистить вывод" @click="output = ''">
            <AppIcon name="trash" />
          </button>
          <div class="bottom-tabs-spacer" />
        </div>
        <div ref="outEl" class="task-output">
          <span v-if="output === '' && !taskRunning" class="task-hint">
            Выбери команду (build / run / test — из секции [commands] файла tinyide.toml) и нажми ▶
          </span>
          <div v-for="(line, i) in output.split('\n')" :key="i" v-html="styledLines(line) || '&nbsp;'" />
        </div>
      </div>
    </template>
  </div>
</template>
