// src/components/ContextMenu.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted } from 'vue';
import { store } from '../store';

const menu = computed(() => store.menu!);

function onDown(e: MouseEvent) {
  const el = (e.target as HTMLElement).closest('.menu');
  if (!el) store.setMenu(null);
}

onMounted(() => window.addEventListener('mousedown', onDown));
onUnmounted(() => window.removeEventListener('mousedown', onDown));

const style = computed(() => {
  const m = menu.value;
  const left = Math.min(m.x, window.innerWidth - 240);
  const top = Math.min(m.y, window.innerHeight - m.items.length * 34 - 40);
  return { left: left + 'px', top: top + 'px' };
});
</script>

<template>
  <div class="menu-overlay">
    <div class="menu" :style="style">
      <template v-for="(item, i) in menu.items" :key="i">
        <div v-if="item === 'sep'" class="menu-sep" />
        <button
          v-else
          class="menu-item"
          :class="{ danger: item.danger }"
          @click="store.setMenu(null); item.run()"
        >
          {{ item.label }}
        </button>
      </template>
    </div>
  </div>
</template>

// src/components/ContextMenu.tsx
import { useEffect, useRef } from 'react';
import type { IdeApi } from '../types';

export default function ContextMenu({ ide }: { ide: IdeApi }) {
  const menu = ide.menu!;
  const ref = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const onDown = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) ide.setMenu(null);
    };
    window.addEventListener('mousedown', onDown);
    return () => window.removeEventListener('mousedown', onDown);
  }, [ide]);

  const left = Math.min(menu.x, window.innerWidth - 240);
  const top = Math.min(menu.y, window.innerHeight - menu.items.length * 34 - 40);

  return (
    <div className="menu-overlay">
      <div ref={ref} className="menu" style={{ left, top }}>
        {menu.items.map((item, i) =>
          item === 'sep' ? (
            <div key={i} className="menu-sep" />
          ) : (
            <button
              key={i}
              className={`menu-item ${item.danger ? 'danger' : ''}`}
              onClick={() => {
                ide.setMenu(null);
                item.run();
              }}
            >
              {item.label}
            </button>
          )
        )}
      </div>
    </div>
  );
}
