// src/components/TabsBar.vue
<script setup lang="ts">
import { store } from '../store';
import LangLogo from '../languages/LangLogo.vue';
import AppIcon from './AppIcon.vue';

const closeTab = (e: MouseEvent, path: string) => {
  e.stopPropagation();
  store.closeTab(path);
};
const midClick = (e: MouseEvent, path: string) => {
  if (e.button === 1) store.closeTab(path);
};
</script>

<template>
  <div class="tabs">
    <div v-if="store.openFiles.length === 0" class="tabs-empty" />
    <div
      v-for="f in store.openFiles"
      :key="f.path"
      class="tab"
      :class="{ active: f.path === store.activePath }"
      :title="f.path"
      @click="store.setActivePath(f.path)"
      @auxclick="midClick($event, f.path)"
    >
      <LangLogo :lang="f.language" :size="14" />
      <span class="tab-name">{{ f.name }}</span>
      <span v-if="store.dirty[f.path]" class="tab-dirty" title="Не сохранено" />
      <button
        v-else
        class="tab-close"
        title="Закрыть (Ctrl+W)"
        @click="closeTab($event, f.path)"
      >
        <AppIcon name="close" :size="12" />
      </button>
    </div>
  </div>
</template>

// src/components/TabsBar.tsx
import type { IdeApi } from '../types';
import { LangLogo } from '../languages/LangLogo';
import { CloseIcon } from './icons';

export default function TabsBar({ ide }: { ide: IdeApi }) {
  const { openFiles, activePath, dirty } = ide;

  return (
    <div className="tabs">
      {openFiles.length === 0 && <div className="tabs-empty" />}
      {openFiles.map((f) => {
        const active = f.path === activePath;
        const isDirty = !!dirty[f.path];
        return (
          <div
            key={f.path}
            className={`tab ${active ? 'active' : ''}`}
            onClick={() => ide.setActivePath(f.path)}
            onAuxClick={(e) => {
              if (e.button === 1) ide.closeTab(f.path);
            }}
            title={f.path}
          >
            <LangLogo lang={f.language} size={14} />
            <span className="tab-name">{f.name}</span>
            {isDirty ? (
              <span className="tab-dirty" title="Не сохранено" />
            ) : (
              <button
                className="tab-close"
                title="Закрыть (Ctrl+W)"
                onClick={(e) => {
                  e.stopPropagation();
                  ide.closeTab(f.path);
                }}
              >
                <CloseIcon size={12} />
              </button>
            )}
          </div>
        );
      })}
    </div>
  );
}
